### ISSUE TITLE
SQLite3::IOException disk I/O error - on new install in Rails 4

### ISSUE THREAD

**Issue by DiegoSalazar** [pboling/rack-insight#32]
After installing rack insight and setting up development.rb as per instructions I get this error. I can see that the rack-insight.sqlite is created in my app root. And even after restarting the server twice I still get the above exception on any page load.

I tried providing a different :database_path with out success.

**Comment by melcher** [comment]
I'm running into the same issue trying to setup on Rails 4.1.7 with postgres. Any suggestions?
```
15:15:29 web.1       | SQLite3::IOException (disk I/O error):
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/statement.rb:108:in `step'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/statement.rb:108:in `block in each'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/statement.rb:107:in `loop'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/statement.rb:107:in `each'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/database.rb:158:in `to_a'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/database.rb:158:in `block in execute'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/database.rb:95:in `prepare'
15:15:29 web.1       |   sqlite3 (1.3.10) lib/sqlite3/database.rb:134:in `execute'
15:15:29 web.1       |   rack-insight (0.6.3) lib/rack/insight/database.rb:123:in `execute'
15:15:29 web.1       |   rack-insight (0.6.3) lib/rack/insight/database.rb:148:in `insert'
15:15:29 web.1       |   rack-insight (0.6.3) lib/rack/insight/database.rb:170:in `store'
15:15:29 web.1       |   rack-insight (0.6.3) lib/rack/insight/request-recorder.rb:12:in `call'
15:15:29 web.1       |   rack (1.5.2) lib/rack/cascade.rb:33:in `block in call'
15:15:29 web.1       |   rack (1.5.2) lib/rack/cascade.rb:24:in `each'
15:15:29 web.1       |   rack (1.5.2) lib/rack/cascade.rb:24:in `call'
15:15:29 web.1       |   rack-toolbar (0.1.4) lib/rack/toolbar.rb:32:in `call'
15:15:29 web.1       |   rack-insight (0.6.3) lib/rack/insight/app.rb:62:in `call'
15:15:29 web.1       |   rack-attack (4.2.0) lib/rack/attack.rb:104:in `call'
15:15:29 web.1       |   rack (1.5.2) lib/rack/etag.rb:23:in `call'
15:15:29 web.1       |   rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
15:15:29 web.1       |   rack (1.5.2) lib/rack/head.rb:11:in `call'
15:15:29 web.1       |   remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
15:15:29 web.1       |   actionpack (4.1.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
```

**Comment by pboling** [comment]
@melcher What environment?  Heroku?

**Comment by pboling** [comment]
For reference, this is a similar issue with connecting to sqlite from a Rack app running on Heroku:
http://stackoverflow.com/questions/25941542/sqlite3ioexception-disk-i-o-error

**Comment by brianbloniarz** [comment]
I saw the same thing in puma under OSX, and turning off multiple worker processes made the issue go away. It may have something to do with multi-process file locking -- I hope to do more debugging. The extended error code in this case was SQLITE_IOERR_LOCK.

**Comment by LongLonghaoran** [comment]
Just remove the spring from your Gemfile.Tested on my MBP. Big Sur
